Repository green-code-initiative/creedengo-java, pull requests merged in 2024-02, with the labels that each got.

#14 [ISSUE 12] Add support for SonarQube 10.4 'DownloadOnlyWhenRequired' feature
  CHANGELOG.md
  pom.xml
Labels: :fire: in progress :fire:, :rocket: enhancement

#6 fix: :bug: Fix issues #228 #233 #235 #240
  CHANGELOG.md
  docker-compose.yml
  pom.xml
  src/main/java/fr/greencodeinitiative/java/JavaCheckRegistrar.java
  src/main/java/fr/greencodeinitiative/java/checks/AvoidConcatenateStringsInLoop.java
  src/main/java/fr/greencodeinitiative/java/checks/AvoidUsingGlobalVariablesCheck.java
  src/main/java/fr/greencodeinitiative/java/checks/UnnecessarilyAssignValuesToVariables.java
  src/main/java/fr/greencodeinitiative/java/checks/UseCorrectForLoop.java
  src/test/files/AvoidConcatenateStringsInLoop.java
  src/test/files/AvoidUsingGlobalVariablesCheck.java
  src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java
  src/test/files/UnnecessarilyAssignValuesToVariablesTestCheckWithEmptyReturn.java
  src/test/files/UseCorrectForLoopCheck.java
  src/test/java/fr/greencodeinitiative/java/JavaCheckRegistrarTest.java
  src/test/java/fr/greencodeinitiative/java/JavaRulesDefinitionTest.java
  src/test/java/fr/greencodeinitiative/java/checks/AvoidConcatenateStringsInLoopTest.java
  src/test/java/fr/greencodeinitiative/java/checks/AvoidUsingGlobalVariablesCheckCheckTest.java
  src/test/java/fr/greencodeinitiative/java/checks/UnnecessarilyAssignValuesToVariablesTest.java
  src/test/java/fr/greencodeinitiative/java/checks/UseCorrectLoopCheckTest.java
Labels: :beginner: good first issue, :card_file_box: rule, :fire: in progress :fire:, :rocket: enhancement

#17 [ISSUE 15] correction NullPointer in EC2
  src/main/java/fr/greencodeinitiative/java/checks/AvoidMultipleIfElseStatement.java
  src/test/files/AvoidMultipleIfElseStatementCompareMethod.java
  src/test/java/fr/greencodeinitiative/java/checks/AvoidMultipleIfElseStatementTest.java
Labels: :syringe: bug
